openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /takeMoney/{id}:
    put:
      tags:
      - banking-controller
      operationId: takeMoney
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: sum
        in: query
        required: true
        schema:
          type: number
          format: double
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: object
  /putMoney/{id}:
    put:
      tags:
      - banking-controller
      operationId: putMoney
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      - name: sum
        in: query
        required: true
        schema:
          type: number
          format: double
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: object
  /getBalance/{id}:
    get:
      tags:
      - banking-controller
      operationId: getBalance
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: object
components: {}
